EagleoutIce/tikzpingus

documentation.tex

25 ci compile of documentation fails miserably

---

tikzpingus-cloak.lib.tex

fix cloak bug overlay

---

.github/workflows/status_check.yaml
.latexmkrc
documentation.tex
indexstyle.ist

Fixing the problem of wrong index.

adding a indexstyle

---

.github/workflows/compile.yaml
.github/workflows/status_check.yaml

Fix compile.yaml

---

build.lua

Did include too much on `l3build ctan`

fixing build file

---

.github/workflows/compile.yaml
.github/workflows/status_check.yaml
README.md
examples/.latexmkrc
examples/spl.tex

Software product line example

---

LICENSE
doc/tikzpingus-doc.tex
tex/tikzpingus-christmas.lib.tex
tex/tikzpingus-cloak.lib.tex
tex/tikzpingus-devil.lib.tex
tex/tikzpingus-emotions.lib.tex
tex/tikzpingus-flags.lib.tex
tex/tikzpingus-formal.lib.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus-glasses.lib.tex
tex/tikzpingus-hats.lib.tex
tex/tikzpingus-horse.lib.tex
tex/tikzpingus-magic.lib.tex
tex/tikzpingus-medieval.lib.tex
tex/tikzpingus-movement.lib.tex
tex/tikzpingus-safe.lib.tex
tex/tikzpingus-science-fiction.lib.tex
tex/tikzpingus-shirts.lib.tex
tex/tikzpingus-signs.lib.tex
tex/tikzpingus-sport.lib.tex
tex/tikzpingus-technology.lib.tex
tex/tikzpingus.sty

happy greeting penguin in the documentation

---

doc/tikzpingus-doc.tex
tex/tikzpingus-emotions.lib.tex
tex/tikzpingus.sty

selectors from packages

---

.github/workflows/checkBrokenLinks.yaml
.github/workflows/compile.yaml
CHANGELOG.md
build.lua

Will use `--future-release` in order to account for the tag to follow

84 validate changelog generation

---

.github/workflows/compile.yaml
.github/workflows/status_check.yaml
README.md
doc/tikzpingus-doc.tex
examples/.latexmkrc
examples/hey-pingu.tex

18 improve preview of the readme

---

doc/tikzpingus-doc.tex

fix fadings on mask and santa

---

examples/hey-pingu.tex

increase line widths

---

tex/tikzpingus.sty

more rounded bill

---

doc/tikzpingus-doc.tex

basic links for predefined styles

---

examples/hey-pingu.tex

add sit to cursive markup in preview 

---

doc/tikzpingus-doc.tex
examples/hey-pingu.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

Now using the heart-eyes heart for the belly

remove font awesome dependency with penguin heart

---

doc/tikzpingus-doc.tex
examples/minimal.tex
examples/spl.tex
tex/tikzpingus.sty

fade out option that does not affect the gadgets

---

doc/tikzpingus-doc.tex

describing the commands for setting defaults with the new commandexplain

---

doc/tikzpingus-doc.tex

explain the commands

---

doc/tikzpingus-doc.tex

fix index ref in key overview

---

doc/tikzpingus-doc.tex

Correct default c3

---

doc/tikzpingus-doc.tex

basic configuration for sheriff star

---

doc/tikzpingus-doc.tex

make sectioning more prominent

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-bee.lib.tex
tex/tikzpingus.sty

117 bee friend

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-horse.lib.tex
tex/tikzpingus.sty

174 knight

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

186 vampire teeth for the bill

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus-hats.lib.tex
tex/tikzpingus.sty

190 a penguin with a witch hat

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

192 a jack o lantern

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-emotions.lib.tex
tex/tikzpingus.sty

198 more critical look

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus.sty

194 steam for the cup

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-christmas.lib.tex
tex/tikzpingus.sty

213 warm hat

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-christmas.lib.tex
tex/tikzpingus.sty

216 present for the penguins

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus.sty

221 fitting bishop wing items

---

doc/tikzpingus-doc.tex

173 bishop

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

219 wooden plank

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-christmas.lib.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

228 snowball

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-fun.lib.tex
tex/tikzpingus.sty

231 magnifier

---

doc/tikzpingus-doc.tex

lot of minor improvements

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus-formal.lib.tex
tex/tikzpingus.sty

205 belts for the penguin

---

tex/tikzpingus.sty

fix: remove rounded corners for wink eyes

---

tex/tikzpingus-science-fiction.lib.tex

Fix Lightsaber in the Firefox PDF viewer

---

tex/tikzpingus-science-fiction.lib.tex

Remove glow marker from lightstaff

---

tex/tikzpingus-emotions.lib.tex
tex/tikzpingus.sty

Use softer `@glow` options for the `blush`

---

doc/tikzpingus-doc.tex

/pingu/banner sticks length is not a color

---

README.md
doc/README-ctan.md
doc/tikzpingus-doc.tex

Remove Todo Markers From the Readme

---

.github/workflows/status_check.yaml
doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus.sty

A fish for penguins

---

doc/tikzpingus-doc.tex
examples/minimal.tex
tex/tikzpingus.sty

So far, this provides the following wing items:
* guitar
* drum sticks
* microphone
The following extras:
* drums
And the following bill shapes:
* open
As well as the following utilities:
* bill above (to bring any bill shape to the front)

Instruments
